apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
##        image: nginx:1.14.2
        image: gcr.io/ashishnabira/helloworldphp:latest
        ports:
        - containerPort: 80

#kind: Service
#apiVersion: v1
#metadata:
#  name: nginx
#spec:
#  selector:
#     run: ngnix
#  ports:
#  - protocol: TCP
#    port: 80
#    targetPort: 80
#  type: LoadBalancer
